name: SGDAFusion
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - pytorch-lightning==1.4.2
      - timm==1.0.22
      - kornia==0.8.1
      - diffusers==0.34.0
      - transformers==4.37.2
      - accelerate==0.28.0
      - einops==0.8.1
      - open-clip-torch==3.3.0
      - pytorch-msssim==1.0.0
      - pyiqa==0.1.12
      - numpy==1.26.1
      - scipy==1.15.3
      - scikit-image==0.20.0
      - scikit-learn==1.7.2
      - opencv-python==4.6.0.66
      - pillow==9.5.0
      - matplotlib==3.10.7
      - imageio==2.37.0
      - albumentations==0.4.3
      - tqdm==4.67.1
      - yacs==0.1.8
      - omegaconf==2.1.1
      - pyyaml==6.0.2
      - tensorboard==2.20.0
      - tensorboardX==2.6.4
      - wandb==0.22.3
      - loguru==0.7.3
      - calflops==0.3.2
      - natsort==8.4.0
      - warmup-scheduler==0.3